version: '3.8'

services:

  minecraft_bedrock:
    image: 'gameservermanagers/gameserver:pw'
    container_name: palworld
    volumes:
      - '/data/servers/palworld:/data'
    restart: unless-stopped
    ports:
      - "8211:8211/udp"
    labels:
      - 'portical.upnp.forward=8211:8211/udp'