version: '3.8'

volumes:
  minecraft_bedrock:
    name: minecraft_bedrock

services:

  minecraft_bedrock:
    image: 'gameservermanagers/gameserver:mcb'
    container_name: minecraft_bedrock
    volumes:
      - 'minecraft_bedrock:/data'
    restart: unless-stopped
    network_mode: lan
    labels:
      - 'portical.upnp.forward=19132:19132/udp'