#!/usr/bin/env bash

function setup() {
  docker context create server-bodar-com --docker "host=ssh://rancher@server.bodar.com:222"
  docker context use server-bodar-com
}

function run-all() {
  for run in applications/*/run
  do (
    cd "$(dirname "$run")"
    ./run
  )
  done
}

function ci() {
  setup
  run-all
}

command="${1-ci}"
set +e; shift; set -Eeo pipefail;
$command "$@"