#!/usr/bin/env bash

function setup() {
  local name="server-bodar-com"

  if ! docker context inspect "${name}" &> /dev/null; then
    docker context create "${name}" --docker "host=ssh://rancher@server.bodar.com:222"
    docker context use "${name}"
  fi

  cp .ssh/config ~/.ssh/config
}

function run-all() {
  for run in applications/*/run
  do (
    cd "$(dirname "$run")"
    ./run
  )
  done
}

function update() {
  setup
  docker pull
  run-all
}

command="${1-update}"
set +e; shift; set -Eeo pipefail;
$command "$@"