version: '3.8'

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=DEBUG"
      - "--entrypoints.websecure.address=:443"
      - "--serversTransport.insecureSkipVerify=true"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/letsencrypt.json"
      - "--certificatesresolvers.letsencrypt.acme.tlsChallenge=true"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/data/servers/traefik:/data'
    restart: unless-stopped
    labels:
      - 'portical.upnp.forward=443:443'
    networks:
      - dmz

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.server.bodar.com`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
    networks:
      - dmz

networks:
  dmz:
    name: dmz
    external: true
