version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: build
          command: ./run update

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context:
            - zerossl
          filters:
            branches:
              only: master