version: '3.8'

services:

  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/run/system-engine.sock:/var/run/system-engine.sock'
      - '/data/servers/portainer:/data'
    ports:
      - '9443:9443/tcp'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`portainer.server.bodar.com`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=zerossl"