version: '3.8'

volumes:
  portainer:
    name: portainer

services:

  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/run/system-engine.sock:/var/run/system-engine.sock'
      - 'portainer:/data'
    ports:
#      - '8000:8000/tcp'
      - '9443:9443/tcp'
    restart: unless-stopped