version: '3.8'

services:

  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/run/system-engine.sock:/var/run/system-engine.sock'
      - '/data/servers/portainer:/data'
    ports:
      - '9000:9000'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.server.bodar.com`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - dmz

networks:
  dmz:
    name: dmz
    external: true