version: '3.8'

services:

  minecraft_bedrock:
    image: 'gameservermanagers/gameserver:mcb'
    container_name: minecraft_bedrock
    volumes:
      - '/data/servers/minecraft_bedrock:/data'
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
    labels:
      - 'portical.upnp.forward=19132:19132/udp'