version: '3.8'

volumes:
  minecraft_bedrock_data:

services:

  minecraft_bedrock_fix:
    image: alpine
    volumes:
      - 'minecraft_bedrock_data:/data'
      - .:/tmp
    command: sh -c "mkdir -p /data/config-lgsm/mcbserver/ && cp -v /tmp/common.cfg /data/config-lgsm/mcbserver/"

  minecraft_bedrock:
    image: 'gameservermanagers/gameserver:mcb'
    container_name: mcbserver
    volumes:
      - 'minecraft_bedrock_data:/data'
    ports:
      - '19132:19132/udp'
    restart: unless-stopped



