#!/usr/bin/env bash

docker compose pull
docker compose up -d

docker cp data/shared/config-lgsm minecraft_bedrock:/data/
docker cp data/shared/serverfiles minecraft_bedrock:/data/


docker cp data/shared/config-lgsm minecraft_bedrock:/data/
docker cp data/shared/serverfiles minecraft_bedrock:/data/
docker cp data/wrlin_survival/serverfiles wrlin_survival:/data/