version: '3.8'

services:

  minecraft_java:
    image: 'gameservermanagers/gameserver:mc'
    container_name: minecraft_java
    volumes:
      - '/data/servers/minecraft_java:/data'
    restart: unless-stopped
    ports:
      - "25565:25565"
    labels:
      - 'portical.upnp.forward=published'