version: '3.8'

volumes:
  minecraft_java:
    name: minecraft_java

services:

  minecraft_java:
    image: 'gameservermanagers/gameserver:mc'
    container_name: minecraft_java
    volumes:
      - 'minecraft_java:/data'
    ports:
      - '25565:25565'
    restart: unless-stopped
